<?php

return [
    'list' => [
        'Is ',
        'Is it ',
        'Is there ',
        'Is there ',
        'Is anyone ',
        'Is anything ',
        'Isn’t it ',
        'Can ',
        'Can they ',
        'Can _COL__VERB__COL_ ',
        'Can I ',
        'Can you ',
        'Can a ',
        'Can\'t you ',
        'Can\'t they ',
        'Can\'t we ',
        'How do you ',
        'How do I ',
        'How can I ',
        'How can you ',
        'How can my ',
        'How does ',
        'How do ',
        'How long ',
        'How are you ',
        'How am I ',
        'How do they ',
        'How did ',
        'How you ',
        'How they ',
        'How we ',
        'How I ',
        'How did ',
        'How don\'t ',
        'How old ',
        'How many ',
        'How tall is ',
        'How tall are ',
        'How much ',
        'How big ',
        'How small ',
        'How large ',
        'How to ',
        'How to increase ',
        'How to improve ',
        'How to find ',
        'How to learn _COL_ for free ',
        'How much does _COL_ cost ',
        'How to make ',
        'How to get rid of ',
        'How to star ',
        'How many ',
        'What ',
        'What do ',
        'What is ',
        'What to ',
        'What are ',
        'What\'s the best time to ',
        'What are the best ways ',
        'What\'s the fastest way ',
        'What\'s a good ',
        'What does ',
        'What is the ',
        'What does ',
        'What time ',
        'What to expect ',
        'What color ',
        'What side ',
        'What holiday ',
        'What would you do ',
        'What would you ',
        'What causes ',
        'What time ',
        'What day ',
        'What should ',
        'What could ',
        'What shouldn\'t ',
        'What can\'t ',
        'What can ',
        'What temp ',
        'What\'s better ',
        'What\'s on ',
        'What\'s the ',
        'What\'s in ',
        'What\'s not ',
        'What\'s the difference between ',
        'When was ',
        'When is ',
        'When do ',
        'When do you ',
        'When does ',
        'When did ',
        'When don\'t ',
        'When do I ',
        'When do they ',
        'When will ',
        'When to ',
        'When are ',
        'When can ',
        'When should ',
        'When shouldn\'t ',
        'When they ',
        'When you ',
        'Where are ',
        'Where is ',
        'Where do ',
        'Where have ',
        'Where\'s the ',
        'Where don\'t ',
        'Where should ',
        'Where can ',
        'Where there ',
        'Where then ',
        'Where was ',
        'Who is ',
        'Who is the ',
        'Who won ',
        'Who doesn\'t ',
        'Who should ',
        'Who can\'t ',
        'Who runs ',
        'Who will ',
        'Who to ',
        'Whose ',
        'Which ',
        'Which ways ',
        'Which blogs ',
        'Which videos ',
        'Which methods ',
        'Which are ',
        'Why is ',
        'Why aren\'t ',
        'Why should ',
        'Why shouldn\'t ',
        'Why can\'t ',
        'Why could ',
        'Why does ',
        'Why do ',
        'Why did ',
        'Why don\'t ',
        'Why am I ',
        'Why you ',
        'Why I ',
        'Why they ',
        'Will ',
        'Will they ',
    ]
];
